name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  run-build:
    runs-on: macos-latest # Required if your build script compiles iOS code via xcodebuild

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/build.sh

      - name: Run build script
        run: ./scripts/build.sh
